Remove baking and finalization commission
Concordium/concordium-scan pull request #128
Opened 2023-11-07 12:30 UTC by schwartz-concordium

## Purpose

Remove any “baking” words in the frontend and remove finalization commission if the amount is zero.

Task: https://concordium.atlassian.net/browse/CBW-1465

## Changes

* The terms baker and baking have been removed for anything which is rendered
* Finalization commissions are only shown when the amount is non zero. This makes the views backward compatible.

## Checklist

- [x] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.

2023-11-07 14:45 UTC, orhoj requested changes

2023-11-07 14:45 UTC, orhoj commented on frontend/src/components/BlockDetails/BlockDetailsTokenomics.vue
> +						console.log(current)
Remove

2023-11-07 14:45 UTC, orhoj commented on frontend/src/components/BlockDetails/BlockDetailsTokenomics.vue
> +					data.block.finalizationRewards.nodes.reduce((acc, current) => {
I think this should probably be a function so that it becomes more obvious why this is here and what it does.

2023-11-07 14:45 UTC, orhoj commented on frontend/src/components/Tokenomics/PaydayAccountReward.vue
> +const showFinalization = computed(() => {
I think it would be nicer and more expressive if this evaluated to a bool instead of a number.

2023-11-07 14:45 UTC, orhoj commented on frontend/src/components/Tokenomics/PaydayPoolReward.vue
> +const showFinalization = computed(() => {
This seems like a duplicate of what you have in `PaydayAccountReward`. Could those classes share more code?

2023-11-07 15:01 UTC, orhoj commented
I am uncertain if it is a requirement or not, but should the URL for viewing a validator also be updated? Right now it is like e.g. https://testnet.ccdscan.io/staking?dcount=1&dentity=baker&did=3113, and I am wondering if it should be https://testnet.ccdscan.io/staking?dcount=1&dentity=validator&did=3113.

2023-11-08 09:54 UTC, schwartz-concordium commented
> I am uncertain if it is a requirement or not, but should the URL for viewing a validator also be updated? Right now it is like e.g. https://testnet.ccdscan.io/staking?dcount=1&dentity=baker&did=3113, and I am wondering if it should be https://testnet.ccdscan.io/staking?dcount=1&dentity=validator&did=3113.


I would expect it should change. I have updated PR and ask for clarification on this.

2023-11-08 11:30 UTC, chportma commented
> > I am uncertain if it is a requirement or not, but should the URL for viewing a validator also be updated? Right now it is like e.g. https://testnet.ccdscan.io/staking?dcount=1&dentity=baker&did=3113, and I am wondering if it should be https://testnet.ccdscan.io/staking?dcount=1&dentity=validator&did=3113.
> 
> I would expect it should change. I have updated PR and ask for clarification on this.

Yes, it would be good to change this too. Maybe for backwards compatibility, the url could still work with “baker”, but whenever we generate a URL, we do it with “validator”?

2023-11-08 11:37 UTC, chportma commented
> ## Purpose
> Remove any “baking” words in the frontend and remove finalization commission if the amount is zero.

I don't mean to be unnecessarily picky, I just want to avoid any confusion: there seems to be a mix-up between finalization rewards and commissions in this description. Finalization rewards should not be displayed if they are 0. The finalization commissions for a pool should not be displayed any more, not conditioned on anything.

2023-11-14 12:23 UTC, shjortConcordium commented on frontend/src/components/RejectionReason/Reasons/BakingRewardCommissionNotInRange.vue
> +		Validation reward commission is not in the valid range for a validator
```suggestion
		Block reward commission is not in the valid range for a validator
```

2023-11-14 12:24 UTC, shjortConcordium commented on frontend/src/components/Tokenomics/ValidationRewards.vue
> +		<template #title>Validation rewards</template>
```suggestion
		<template #title>Block rewards</template>
```

2023-11-14 12:25 UTC, shjortConcordium commented on frontend/src/components/TransactionEventList/Events/BakerSetBakingRewardCommission.vue
> +		Validator <BakerLink :id="event.bakerId" /> set validation reward commission
```suggestion
		Validator <BakerLink :id="event.bakerId" /> set block reward commission
```

2023-11-14 12:25 UTC, shjortConcordium commented on frontend/src/components/TransactionEventList/Events/ChainUpdateEnqueued.vue
> +					Passive validation commission
```suggestion
					Passive block commission
```

2023-11-14 12:43 UTC, schwartz-concordium commented
> > > I am uncertain if it is a requirement or not, but should the URL for viewing a validator also be updated? Right now it is like e.g. https://testnet.ccdscan.io/staking?dcount=1&dentity=baker&did=3113, and I am wondering if it should be https://testnet.ccdscan.io/staking?dcount=1&dentity=validator&did=3113.
> > 
> > 
> > I would expect it should change. I have updated PR and ask for clarification on this.
> 
> Yes, it would be good to change this too. Maybe for backwards compatibility, the url could still work with “baker”, but whenever we generate a URL, we do it with “validator”?

Works now with both links. Using old baker will have you routed to url with validator.

2023-11-14 13:14 UTC, shjortConcordium commented on frontend/src/components/BakerDetails/BakerDetailsPoolContent.vue
> +					<template #title>Validation commission</template>
```suggestion
					<template #title>Block commission</template>
```
I guess I missed one.

2023-11-14 13:14 UTC, shjortConcordium commented on frontend/src/components/BakerDetails/BakerDetailsPoolRewardsItem.vue
> +						<span class="float-left inline-block pt-2">Validation rewards</span>
```suggestion
						<span class="float-left inline-block pt-2">Block rewards</span>
```

2023-11-14 13:15 UTC, shjortConcordium commented on frontend/src/components/NodeDetails/NodeDetailsContent.vue
> +					<template #title>Validation Committee</template>
```suggestion
					<template #title>Block Committee</template>
```

2023-11-14 13:15 UTC, shjortConcordium commented on frontend/src/components/PassiveDelegation/PassiveDelegationContent.vue
> +					<template #title>Validation commission</template>
```suggestion
					<template #title>Block commission</template>
```

2023-11-14 13:17 UTC, shjortConcordium commented on frontend/src/components/TransactionEventList/Events/ChainUpdateEnqueued.vue
> +					Validation commission range
```suggestion
					Block commission range
```

2023-11-14 13:18 UTC, shjortConcordium commented on frontend/src/components/PassiveDelegation/PassiveDelegationRewardsItem.vue
> +						Validation reward:
```suggestion
						Block reward:
```

2023-11-14 18:28 UTC, merged